### ISSUE TITLE
esp8266好像不支持多线程库

### ISSUE THREAD

**Issue by earth-hotfix** [majoson-chen/micro_route#1]
Debug Info:
Traceback (most recent call last):
  File "main.py", line 1, in <module>
ImportError: no module named '_thread

**Comment by majoson-chen** [comment]
对的, 在 esp8266 上没有 _thread 库, 所以请使用非阻塞的监听方法

**Comment by earth-hotfix** [comment]
我正在diy这块开发板子，有没有交流群或者联系方式可以和你交流吗

**Comment by majoson-chen** [comment]
莫得. 我也是散户
